import {getLevelCompletionReward, MATCH_REWARD} from './coinRewards';

export const PRODUCT_ASSETS = {
  apple: require('../assets/splash elements/apple without bg.png'),
  milk: require('../assets/splash elements/milk bottle without bg.png'),
  juice: require('../assets/splash elements/orange bottle wthout bg.png'),
  can: require('../assets/splash elements/red bottle without bg.png'),
  blueMilk: require('../assets/merglix game elments/blue milk bottle.png'),
  blueJuice: require('../assets/merglix game elments/blue juice bottle.png'),
  orangeBottle: require('../assets/merglix game elments/orange bottle.png'),
  redChips: require('../assets/merglix game elments/red chips cane.png'),
  greenHerbal: require('../assets/merglix game elments/Green herbal bottle.png'),
  blueFruit: require('../assets/merglix game elments/blue fruit bottle.png'),
  greenBottle: require('../assets/merglix game elments/Green bottle.png'),
  greenFruit: require('../assets/merglix game elments/green fruit bottle.png'),
  level3Milk: require('../assets/merglix game elments/milk bottle.png'),
  orangeBottleAlt: require('../assets/merglix game elments/orange bottle-1.png'),
  orangeCan: require('../assets/merglix game elments/orange cane.png'),
  teddy: require('../assets/merglix game elments/Artboard 3.png'),
  duck: require('../assets/merglix game elments/Artboard 4.png'),
  corn: require('../assets/merglix game elments/corn.png'),
  grapes: require('../assets/merglix game elments/Grapes.png'),
  lemon: require('../assets/merglix game elments/lemon.png'),
  pineapple: require('../assets/merglix game elments/Pineapple.png'),
  sooperBiscuit: require('../assets/merglix game elments/sooper biscuit.png'),
  watermelon: require('../assets/merglix game elments/watermelon.png'),
  strawberry: require('../assets/merglix game elments/stabbery.png'),
  caramelTeddy: require('../assets/merglix game elments/Glossy Caramel Teddy Bear with Red Bow.png'),
  cricketBatBall: require('../assets/merglix game elments/Glossy Cricket Bat and Ball Duo.png'),
  fieldHockey: require('../assets/merglix game elments/Glossy Field Hockey Stick and Ball.png'),
  greenMilkPak: require('../assets/merglix game elments/Glossy Green Milk Pak Carton .png'),
  redNimcoMix: require('../assets/merglix game elments/Glossy Red Nimco Mix Snack Bag.png'),
  redTomatoPair: require('../assets/merglix game elments/Glossy Red Tomato Pair.png'),
  olpersMilk: require('../assets/merglix game elments/OLPERS Super Saver Milk Carton.png'),
  shahiNimco: require('../assets/merglix game elments/Shahi Nimco Savory Mix Packet.png'),
  plushFrog: require('../assets/merglix game elments/Adorable Plush Frog Sticker.png'),
};

export const SHELF_ASSETS = {
  classic3: require('../assets/cupboard with 3 shelf.png'),
  classic4: require('../assets/cupboard with 4 shelf.png'),
  classic5: require('../assets/merglix game elments/cupboard with 5 shelf.png'),
  classic6: require('../assets/merglix game elments/cupboard with 6 shelf.png'),
  classic7: require('../assets/merglix game elments/cupboard with 7 shelf.png'),
};

export function getLevelTimerSeconds(level) {
  const safeLevel = Math.max(1, Math.floor(Number(level) || 1));
  return 60 + Math.floor((safeLevel - 1) / 10) * 10;
}

function levelConfig({level, rows, columns, productTypes, copiesByType,
  difficulty, targetMatches}) {
  const totalItemCount = Object.values(copiesByType)
    .reduce((total, count) => total + count, 0);
  const durationSeconds = getLevelTimerSeconds(level);
  return {
    id: level,
    level,
    rows,
    columns,
    shelfCount: rows,
    productTypes,
    productTypeCount: productTypes.length,
    copiesByType,
    matchSize: 3,
    matchCount: targetMatches,
    targetMatches,
    totalItemCount,
    matchReward: MATCH_REWARD,
    completionReward: getLevelCompletionReward(level),
    durationSeconds,
    timerSeconds: durationSeconds,
    difficulty,
    shelf: `classic${rows}`,
    generatedShelves: false,
  };
}

export const LEVEL_CONFIGS = {
  1: levelConfig({level: 1, rows: 3, columns: 4,
    productTypes: ['apple', 'milk', 'can'],
    copiesByType: {apple: 6, milk: 3, can: 3},
    targetMatches: 4, difficulty: 'tutorial'}),
  2: levelConfig({level: 2, rows: 3, columns: 5,
    productTypes: ['apple', 'milk', 'can'],
    copiesByType: {apple: 6, milk: 6, can: 3},
    targetMatches: 5, difficulty: 'very-easy'}),
  3: levelConfig({level: 3, rows: 3, columns: 5,
    productTypes: ['apple', 'milk', 'juice', 'can'],
    copiesByType: {apple: 6, milk: 3, juice: 3, can: 3},
    targetMatches: 5, difficulty: 'easy'}),
  4: levelConfig({level: 4, rows: 3, columns: 6,
    productTypes: ['apple', 'milk', 'juice', 'can'],
    copiesByType: {apple: 6, milk: 6, juice: 3, can: 3},
    targetMatches: 6, difficulty: 'easy'}),
  5: levelConfig({level: 5, rows: 4, columns: 6,
    productTypes: ['apple', 'milk', 'juice', 'can'],
    copiesByType: {apple: 6, milk: 6, juice: 6, can: 6},
    targetMatches: 8, difficulty: 'easy-plus'}),
  6: levelConfig({level: 6, rows: 4, columns: 6,
    productTypes: ['blueFruit', 'blueJuice', 'blueMilk', 'greenHerbal', 'redChips'],
    copiesByType: {blueFruit: 6, blueJuice: 6, blueMilk: 6, greenHerbal: 3, redChips: 3},
    targetMatches: 8, difficulty: 'medium-low'}),
  7: levelConfig({level: 7, rows: 4, columns: 6,
    productTypes: ['blueFruit', 'blueJuice', 'blueMilk', 'greenHerbal', 'orangeBottle'],
    copiesByType: {blueFruit: 6, blueJuice: 6, blueMilk: 6, greenHerbal: 3, orangeBottle: 3},
    targetMatches: 8, difficulty: 'medium'}),
  8: levelConfig({level: 8, rows: 4, columns: 6,
    productTypes: ['blueFruit', 'blueJuice', 'level3Milk', 'greenFruit', 'orangeCan'],
    copiesByType: {blueFruit: 6, blueJuice: 6, level3Milk: 6, greenFruit: 3, orangeCan: 3},
    targetMatches: 8, difficulty: 'medium'}),
  9: levelConfig({level: 9, rows: 4, columns: 6,
    productTypes: ['blueFruit', 'blueJuice', 'blueMilk', 'greenFruit', 'orangeCan', 'redChips'],
    copiesByType: {blueFruit: 3, blueJuice: 6, blueMilk: 6, greenFruit: 3, orangeCan: 3, redChips: 3},
    targetMatches: 8, difficulty: 'medium-plus'}),
  10: levelConfig({level: 10, rows: 4, columns: 6,
    productTypes: ['greenBottle', 'greenHerbal', 'level3Milk', 'orangeBottle', 'orangeBottleAlt', 'orangeCan'],
    copiesByType: {greenBottle: 6, greenHerbal: 6, level3Milk: 3, orangeBottle: 3, orangeBottleAlt: 3, orangeCan: 3},
    targetMatches: 8, difficulty: 'first-challenge'}),
  11: levelConfig({level: 11, rows: 4, columns: 6,
    productTypes: ['apple', 'milk', 'can', 'juice', 'blueFruit', 'blueMilk', 'orangeBottle', 'redChips'],
    copiesByType: {apple: 3, milk: 3, can: 3, juice: 3, blueFruit: 3, blueMilk: 3, orangeBottle: 3, redChips: 3},
    targetMatches: 8, difficulty: 'medium-entry'}),
  12: levelConfig({level: 12, rows: 4, columns: 6,
    productTypes: ['juice', 'blueMilk', 'orangeBottle', 'greenHerbal', 'apple', 'blueJuice', 'greenBottle', 'orangeCan'],
    copiesByType: {juice: 3, blueMilk: 3, orangeBottle: 3, greenHerbal: 3, apple: 3, blueJuice: 3, greenBottle: 3, orangeCan: 3},
    targetMatches: 8, difficulty: 'medium-entry'}),
  13: levelConfig({level: 13, rows: 4, columns: 6,
    productTypes: ['blueFruit', 'blueJuice', 'level3Milk', 'redChips', 'greenBottle', 'orangeCan', 'greenFruit', 'orangeBottleAlt'],
    copiesByType: {blueFruit: 3, blueJuice: 3, level3Milk: 3, redChips: 3, greenBottle: 3, orangeCan: 3, greenFruit: 3, orangeBottleAlt: 3},
    targetMatches: 8, difficulty: 'medium'}),
  14: levelConfig({level: 14, rows: 4, columns: 6,
    productTypes: ['milk', 'can', 'greenFruit', 'orangeBottleAlt', 'blueMilk', 'greenHerbal', 'redChips', 'orangeCan'],
    copiesByType: {milk: 3, can: 3, greenFruit: 3, orangeBottleAlt: 3, blueMilk: 3, greenHerbal: 3, redChips: 3, orangeCan: 3},
    targetMatches: 8, difficulty: 'medium'}),
  15: levelConfig({level: 15, rows: 4, columns: 6,
    productTypes: ['apple', 'juice', 'blueJuice', 'redChips', 'orangeBottle', 'greenBottle', 'level3Milk', 'greenHerbal'],
    copiesByType: {apple: 3, juice: 3, blueJuice: 3, redChips: 3, orangeBottle: 3, greenBottle: 3, level3Milk: 3, greenHerbal: 3},
    targetMatches: 8, difficulty: 'medium'}),
  16: levelConfig({level: 16, rows: 5, columns: 6,
    productTypes: ['blueFruit', 'blueMilk', 'greenHerbal', 'orangeCan', 'redChips', 'apple', 'milk', 'blueJuice', 'greenBottle', 'orangeBottle'],
    copiesByType: {blueFruit: 3, blueMilk: 3, greenHerbal: 3, orangeCan: 3, redChips: 3, apple: 3, milk: 3, blueJuice: 3, greenBottle: 3, orangeBottle: 3},
    targetMatches: 10, difficulty: 'medium-plus'}),
  17: levelConfig({level: 17, rows: 5, columns: 6,
    productTypes: ['milk', 'can', 'blueJuice', 'greenFruit', 'orangeBottleAlt', 'level3Milk', 'redChips', 'juice', 'blueFruit', 'greenHerbal'],
    copiesByType: {milk: 3, can: 3, blueJuice: 3, greenFruit: 3, orangeBottleAlt: 3, level3Milk: 3, redChips: 3, juice: 3, blueFruit: 3, greenHerbal: 3},
    targetMatches: 10, difficulty: 'medium-plus'}),
  18: levelConfig({level: 18, rows: 5, columns: 6,
    productTypes: ['apple', 'juice', 'orangeBottle', 'blueFruit', 'greenBottle', 'blueMilk', 'orangeCan', 'can', 'redChips', 'orangeBottleAlt'],
    copiesByType: {apple: 3, juice: 3, orangeBottle: 3, blueFruit: 3, greenBottle: 3, blueMilk: 3, orangeCan: 3, can: 3, redChips: 3, orangeBottleAlt: 3},
    targetMatches: 10, difficulty: 'medium-plus'}),
  19: levelConfig({level: 19, rows: 5, columns: 6,
    productTypes: ['blueFruit', 'blueJuice', 'greenHerbal', 'greenFruit', 'orangeBottleAlt', 'orangeCan', 'redChips', 'level3Milk', 'milk', 'can'],
    copiesByType: {blueFruit: 3, blueJuice: 3, greenHerbal: 3, greenFruit: 3, orangeBottleAlt: 3, orangeCan: 3, redChips: 3, level3Milk: 3, milk: 3, can: 3},
    targetMatches: 10, difficulty: 'hard-entry'}),
  20: levelConfig({level: 20, rows: 5, columns: 6,
    productTypes: ['apple', 'milk', 'can', 'juice', 'blueMilk', 'greenBottle', 'orangeBottle', 'redChips', 'blueFruit', 'greenFruit'],
    copiesByType: {apple: 3, milk: 3, can: 3, juice: 3, blueMilk: 3, greenBottle: 3, orangeBottle: 3, redChips: 3, blueFruit: 3, greenFruit: 3},
    targetMatches: 10, difficulty: 'challenge'}),
  21: levelConfig({level: 21, rows: 5, columns: 6,
    productTypes: ['teddy', 'juice', 'blueJuice', 'blueMilk', 'greenBottle', 'greenHerbal', 'level3Milk', 'orangeBottleAlt', 'orangeCan', 'redChips'],
    copiesByType: {teddy: 3, juice: 3, blueJuice: 3, blueMilk: 3, greenBottle: 3, greenHerbal: 3, level3Milk: 3, orangeBottleAlt: 3, orangeCan: 3, redChips: 3},
    targetMatches: 10, difficulty: 'hard'}),
  22: levelConfig({level: 22, rows: 5, columns: 6,
    productTypes: ['teddy', 'can', 'blueFruit', 'blueJuice', 'greenFruit', 'greenHerbal', 'level3Milk', 'orangeBottle', 'orangeCan', 'redChips'],
    copiesByType: {teddy: 3, can: 3, blueFruit: 3, blueJuice: 3, greenFruit: 3, greenHerbal: 3, level3Milk: 3, orangeBottle: 3, orangeCan: 3, redChips: 3},
    targetMatches: 10, difficulty: 'hard'}),
  23: levelConfig({level: 23, rows: 5, columns: 6,
    productTypes: ['teddy', 'milk', 'juice', 'can', 'blueFruit', 'blueMilk', 'greenBottle', 'greenFruit', 'orangeBottleAlt', 'redChips'],
    copiesByType: {teddy: 3, milk: 3, juice: 3, can: 3, blueFruit: 3, blueMilk: 3, greenBottle: 3, greenFruit: 3, orangeBottleAlt: 3, redChips: 3},
    targetMatches: 10, difficulty: 'hard'}),
  24: levelConfig({level: 24, rows: 5, columns: 6,
    productTypes: ['teddy', 'can', 'blueFruit', 'blueJuice', 'blueMilk', 'greenBottle', 'greenHerbal', 'orangeBottle', 'orangeBottleAlt', 'orangeCan'],
    copiesByType: {teddy: 3, can: 3, blueFruit: 3, blueJuice: 3, blueMilk: 3, greenBottle: 3, greenHerbal: 3, orangeBottle: 3, orangeBottleAlt: 3, orangeCan: 3},
    targetMatches: 10, difficulty: 'hard-plus'}),
  25: levelConfig({level: 25, rows: 5, columns: 6,
    productTypes: ['teddy', 'blueJuice', 'apple', 'milk', 'blueFruit', 'greenFruit', 'greenHerbal', 'orangeBottle', 'orangeCan', 'redChips'],
    copiesByType: {teddy: 3, blueJuice: 3, apple: 3, milk: 3, blueFruit: 3, greenFruit: 3, greenHerbal: 3, orangeBottle: 3, orangeCan: 3, redChips: 3},
    targetMatches: 10, difficulty: 'milestone-hard'}),
  26: levelConfig({level: 26, rows: 5, columns: 6,
    productTypes: ['apple', 'greenFruit', 'juice', 'can', 'blueJuice', 'blueMilk', 'greenBottle', 'level3Milk', 'orangeBottleAlt', 'redChips'],
    copiesByType: {apple: 3, greenFruit: 3, juice: 3, can: 3, blueJuice: 3, blueMilk: 3, greenBottle: 3, level3Milk: 3, orangeBottleAlt: 3, redChips: 3},
    targetMatches: 10, difficulty: 'hard-plus'}),
  27: levelConfig({level: 27, rows: 5, columns: 6,
    productTypes: ['can', 'blueJuice', 'apple', 'milk', 'blueFruit', 'greenFruit', 'greenHerbal', 'orangeBottle', 'orangeCan', 'level3Milk'],
    copiesByType: {can: 3, blueJuice: 3, apple: 3, milk: 3, blueFruit: 3, greenFruit: 3, greenHerbal: 3, orangeBottle: 3, orangeCan: 3, level3Milk: 3},
    targetMatches: 10, difficulty: 'advanced'}),
  28: levelConfig({level: 28, rows: 5, columns: 6,
    productTypes: ['milk', 'blueMilk', 'juice', 'can', 'blueFruit', 'blueJuice', 'greenBottle', 'greenHerbal', 'orangeBottleAlt', 'orangeCan'],
    copiesByType: {milk: 3, blueMilk: 3, juice: 3, can: 3, blueFruit: 3, blueJuice: 3, greenBottle: 3, greenHerbal: 3, orangeBottleAlt: 3, orangeCan: 3},
    targetMatches: 10, difficulty: 'advanced'}),
  29: levelConfig({level: 29, rows: 5, columns: 6,
    productTypes: ['duck', 'can', 'apple', 'milk', 'blueJuice', 'blueMilk', 'greenFruit', 'level3Milk', 'orangeBottle', 'redChips'],
    copiesByType: {duck: 3, can: 3, apple: 3, milk: 3, blueJuice: 3, blueMilk: 3, greenFruit: 3, level3Milk: 3, orangeBottle: 3, redChips: 3},
    targetMatches: 10, difficulty: 'advanced-hard'}),
  30: levelConfig({level: 30, rows: 5, columns: 6,
    productTypes: ['duck', 'orangeCan', 'juice', 'can', 'blueFruit', 'blueMilk', 'greenBottle', 'greenFruit', 'orangeBottleAlt', 'redChips'],
    copiesByType: {duck: 3, orangeCan: 3, juice: 3, can: 3, blueFruit: 3, blueMilk: 3, greenBottle: 3, greenFruit: 3, orangeBottleAlt: 3, redChips: 3},
    targetMatches: 10, difficulty: 'milestone-challenge'}),
  31: levelConfig({level: 31, rows: 5, columns: 6,
    productTypes: ['apple', 'milk', 'juice', 'can', 'blueFruit', 'blueJuice', 'greenBottle', 'greenHerbal', 'orangeBottle', 'orangeCan'],
    copiesByType: {apple: 3, milk: 3, juice: 3, can: 3, blueFruit: 3, blueJuice: 3, greenBottle: 3, greenHerbal: 3, orangeBottle: 3, orangeCan: 3},
    targetMatches: 10, difficulty: 'advanced-entry'}),
  32: levelConfig({level: 32, rows: 5, columns: 6,
    productTypes: ['milk', 'can', 'blueFruit', 'blueMilk', 'greenFruit', 'greenHerbal', 'level3Milk', 'orangeBottleAlt', 'orangeCan', 'redChips'],
    copiesByType: {milk: 3, can: 3, blueFruit: 3, blueMilk: 3, greenFruit: 3, greenHerbal: 3, level3Milk: 3, orangeBottleAlt: 3, orangeCan: 3, redChips: 3},
    targetMatches: 10, difficulty: 'advanced'}),
  33: levelConfig({level: 33, rows: 5, columns: 6,
    productTypes: ['apple', 'juice', 'can', 'blueFruit', 'blueJuice', 'blueMilk', 'greenBottle', 'greenFruit', 'orangeBottleAlt', 'redChips'],
    copiesByType: {apple: 3, juice: 3, can: 3, blueFruit: 3, blueJuice: 3, blueMilk: 3, greenBottle: 3, greenFruit: 3, orangeBottleAlt: 3, redChips: 3},
    targetMatches: 10, difficulty: 'advanced'}),
  34: levelConfig({level: 34, rows: 5, columns: 6,
    productTypes: ['apple', 'milk', 'juice', 'blueJuice', 'blueMilk', 'greenBottle', 'greenHerbal', 'level3Milk', 'orangeBottle', 'orangeCan'],
    copiesByType: {apple: 3, milk: 3, juice: 3, blueJuice: 3, blueMilk: 3, greenBottle: 3, greenHerbal: 3, level3Milk: 3, orangeBottle: 3, orangeCan: 3},
    targetMatches: 10, difficulty: 'advanced-plus'}),
  35: levelConfig({level: 35, rows: 5, columns: 6,
    productTypes: ['teddy', 'duck', 'can', 'blueFruit', 'blueMilk', 'greenFruit', 'greenHerbal', 'level3Milk', 'orangeBottleAlt', 'redChips'],
    copiesByType: {teddy: 3, duck: 3, can: 3, blueFruit: 3, blueMilk: 3, greenFruit: 3, greenHerbal: 3, level3Milk: 3, orangeBottleAlt: 3, redChips: 3},
    targetMatches: 10, difficulty: 'advanced-milestone'}),
  36: levelConfig({level: 36, rows: 5, columns: 6,
    productTypes: ['apple', 'milk', 'juice', 'blueFruit', 'blueJuice', 'greenBottle', 'greenHerbal', 'orangeBottle', 'orangeCan', 'redChips'],
    copiesByType: {apple: 3, milk: 3, juice: 3, blueFruit: 3, blueJuice: 3, greenBottle: 3, greenHerbal: 3, orangeBottle: 3, orangeCan: 3, redChips: 3},
    targetMatches: 10, difficulty: 'advanced-hard'}),
  37: levelConfig({level: 37, rows: 5, columns: 6,
    productTypes: ['teddy', 'milk', 'can', 'blueJuice', 'blueMilk', 'greenBottle', 'greenFruit', 'level3Milk', 'orangeBottleAlt', 'orangeCan'],
    copiesByType: {teddy: 3, milk: 3, can: 3, blueJuice: 3, blueMilk: 3, greenBottle: 3, greenFruit: 3, level3Milk: 3, orangeBottleAlt: 3, orangeCan: 3},
    targetMatches: 10, difficulty: 'advanced-hard'}),
  38: levelConfig({level: 38, rows: 5, columns: 6,
    productTypes: ['duck', 'apple', 'juice', 'can', 'blueFruit', 'blueMilk', 'greenHerbal', 'level3Milk', 'orangeBottle', 'redChips'],
    copiesByType: {duck: 3, apple: 3, juice: 3, can: 3, blueFruit: 3, blueMilk: 3, greenHerbal: 3, level3Milk: 3, orangeBottle: 3, redChips: 3},
    targetMatches: 10, difficulty: 'advanced-hard-plus'}),
  39: levelConfig({level: 39, rows: 5, columns: 6,
    productTypes: ['teddy', 'duck', 'milk', 'blueFruit', 'blueJuice', 'greenBottle', 'greenFruit', 'orangeBottle', 'orangeBottleAlt', 'orangeCan'],
    copiesByType: {teddy: 3, duck: 3, milk: 3, blueFruit: 3, blueJuice: 3, greenBottle: 3, greenFruit: 3, orangeBottle: 3, orangeBottleAlt: 3, orangeCan: 3},
    targetMatches: 10, difficulty: 'expert-entry'}),
  40: levelConfig({level: 40, rows: 5, columns: 6,
    productTypes: ['teddy', 'duck', 'apple', 'can', 'blueJuice', 'blueMilk', 'greenFruit', 'greenHerbal', 'level3Milk', 'redChips'],
    copiesByType: {teddy: 3, duck: 3, apple: 3, can: 3, blueJuice: 3, blueMilk: 3, greenFruit: 3, greenHerbal: 3, level3Milk: 3, redChips: 3},
    targetMatches: 10, difficulty: 'expert-milestone'}),
  41: levelConfig({level: 41, rows: 5, columns: 6,
    productTypes: ['corn', 'milk', 'juice', 'can', 'blueFruit', 'blueJuice', 'greenBottle', 'greenFruit', 'orangeBottle', 'redChips'],
    copiesByType: {corn: 3, milk: 3, juice: 3, can: 3, blueFruit: 3, blueJuice: 3, greenBottle: 3, greenFruit: 3, orangeBottle: 3, redChips: 3},
    targetMatches: 10, difficulty: 'expert'}),
  42: levelConfig({level: 42, rows: 5, columns: 6,
    productTypes: ['corn', 'milk', 'can', 'blueFruit', 'blueMilk', 'greenHerbal', 'level3Milk', 'orangeBottleAlt', 'orangeCan', 'redChips'],
    copiesByType: {corn: 3, milk: 3, can: 3, blueFruit: 3, blueMilk: 3, greenHerbal: 3, level3Milk: 3, orangeBottleAlt: 3, orangeCan: 3, redChips: 3},
    targetMatches: 10, difficulty: 'expert'}),
  43: levelConfig({level: 43, rows: 5, columns: 6,
    productTypes: ['corn', 'duck', 'apple', 'juice', 'blueFruit', 'blueJuice', 'blueMilk', 'greenBottle', 'greenFruit', 'orangeBottle'],
    copiesByType: {corn: 3, duck: 3, apple: 3, juice: 3, blueFruit: 3, blueJuice: 3, blueMilk: 3, greenBottle: 3, greenFruit: 3, orangeBottle: 3},
    targetMatches: 10, difficulty: 'expert-plus'}),
  44: levelConfig({level: 44, rows: 5, columns: 6,
    productTypes: ['corn', 'teddy', 'duck', 'milk', 'can', 'blueJuice', 'greenBottle', 'greenHerbal', 'level3Milk', 'orangeBottleAlt'],
    copiesByType: {corn: 3, teddy: 3, duck: 3, milk: 3, can: 3, blueJuice: 3, greenBottle: 3, greenHerbal: 3, level3Milk: 3, orangeBottleAlt: 3},
    targetMatches: 10, difficulty: 'expert-plus'}),
  45: levelConfig({level: 45, rows: 5, columns: 6,
    productTypes: ['corn', 'teddy', 'duck', 'apple', 'juice', 'blueFruit', 'blueMilk', 'greenFruit', 'greenHerbal', 'orangeBottle'],
    copiesByType: {corn: 3, teddy: 3, duck: 3, apple: 3, juice: 3, blueFruit: 3, blueMilk: 3, greenFruit: 3, greenHerbal: 3, orangeBottle: 3},
    targetMatches: 10, difficulty: 'expert-challenge'}),
  46: levelConfig({level: 46, rows: 5, columns: 6,
    productTypes: ['corn', 'grapes', 'lemon', 'blueFruit', 'blueJuice', 'greenBottle', 'greenHerbal', 'level3Milk', 'orangeBottleAlt', 'redChips'],
    copiesByType: {corn: 3, grapes: 3, lemon: 3, blueFruit: 3, blueJuice: 3, greenBottle: 3, greenHerbal: 3, level3Milk: 3, orangeBottleAlt: 3, redChips: 3},
    targetMatches: 10, difficulty: 'expert-hard'}),
  47: levelConfig({level: 47, rows: 5, columns: 6,
    productTypes: ['corn', 'grapes', 'lemon', 'teddy', 'apple', 'blueMilk', 'greenBottle', 'greenFruit', 'level3Milk', 'orangeBottle'],
    copiesByType: {corn: 3, grapes: 3, lemon: 3, teddy: 3, apple: 3, blueMilk: 3, greenBottle: 3, greenFruit: 3, level3Milk: 3, orangeBottle: 3},
    targetMatches: 10, difficulty: 'expert-hard'}),
  48: levelConfig({level: 48, rows: 5, columns: 6,
    productTypes: ['corn', 'grapes', 'lemon', 'duck', 'blueFruit', 'blueJuice', 'blueMilk', 'greenHerbal', 'orangeBottle', 'orangeBottleAlt'],
    copiesByType: {corn: 3, grapes: 3, lemon: 3, duck: 3, blueFruit: 3, blueJuice: 3, blueMilk: 3, greenHerbal: 3, orangeBottle: 3, orangeBottleAlt: 3},
    targetMatches: 10, difficulty: 'expert-hard-plus'}),
  49: levelConfig({level: 49, rows: 5, columns: 6,
    productTypes: ['corn', 'grapes', 'lemon', 'teddy', 'duck', 'blueFruit', 'blueMilk', 'greenBottle', 'greenFruit', 'orangeBottleAlt'],
    copiesByType: {corn: 3, grapes: 3, lemon: 3, teddy: 3, duck: 3, blueFruit: 3, blueMilk: 3, greenBottle: 3, greenFruit: 3, orangeBottleAlt: 3},
    targetMatches: 10, difficulty: 'master-entry'}),
  50: levelConfig({level: 50, rows: 5, columns: 6,
    productTypes: ['corn', 'grapes', 'lemon', 'teddy', 'duck', 'blueJuice', 'greenHerbal', 'level3Milk', 'orangeBottle', 'orangeCan'],
    copiesByType: {corn: 3, grapes: 3, lemon: 3, teddy: 3, duck: 3, blueJuice: 3, greenHerbal: 3, level3Milk: 3, orangeBottle: 3, orangeCan: 3},
    targetMatches: 10, difficulty: 'world-1-finale'}),
  51: levelConfig({level: 51, rows: 6, columns: 6,
    productTypes: ['pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'apple', 'milk', 'blueFruit', 'blueJuice', 'greenBottle', 'orangeBottle', 'redChips'],
    copiesByType: {pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, apple: 3, milk: 3, blueFruit: 3, blueJuice: 3, greenBottle: 3, orangeBottle: 3, redChips: 3},
    targetMatches: 12, difficulty: 'world-2-entry'}),
  52: levelConfig({level: 52, rows: 6, columns: 6,
    productTypes: ['pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'teddy', 'can', 'blueMilk', 'greenFruit', 'greenHerbal', 'level3Milk', 'orangeCan'],
    copiesByType: {pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, teddy: 3, can: 3, blueMilk: 3, greenFruit: 3, greenHerbal: 3, level3Milk: 3, orangeCan: 3},
    targetMatches: 12, difficulty: 'world-2-easy'}),
  53: levelConfig({level: 53, rows: 6, columns: 6,
    productTypes: ['pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'duck', 'juice', 'blueFruit', 'blueMilk', 'greenBottle', 'orangeBottleAlt', 'redChips'],
    copiesByType: {pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, duck: 3, juice: 3, blueFruit: 3, blueMilk: 3, greenBottle: 3, orangeBottleAlt: 3, redChips: 3},
    targetMatches: 12, difficulty: 'world-2-easy-plus'}),
  54: levelConfig({level: 54, rows: 6, columns: 6,
    productTypes: ['pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'teddy', 'duck', 'milk', 'blueJuice', 'greenFruit', 'level3Milk', 'orangeBottle'],
    copiesByType: {pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, teddy: 3, duck: 3, milk: 3, blueJuice: 3, greenFruit: 3, level3Milk: 3, orangeBottle: 3},
    targetMatches: 12, difficulty: 'world-2-medium'}),
  55: levelConfig({level: 55, rows: 6, columns: 6,
    productTypes: ['pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'apple', 'can', 'blueFruit', 'greenHerbal', 'orangeBottle', 'orangeCan', 'redChips'],
    copiesByType: {pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, apple: 3, can: 3, blueFruit: 3, greenHerbal: 3, orangeBottle: 3, orangeCan: 3, redChips: 3},
    targetMatches: 12, difficulty: 'world-2-milestone'}),
  56: levelConfig({level: 56, rows: 6, columns: 6,
    productTypes: ['watermelon', 'strawberry', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'blueFruit', 'blueMilk', 'greenBottle', 'orangeBottleAlt', 'redChips'],
    copiesByType: {watermelon: 3, strawberry: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, blueFruit: 3, blueMilk: 3, greenBottle: 3, orangeBottleAlt: 3, redChips: 3},
    targetMatches: 12, difficulty: 'world-2-medium-plus'}),
  57: levelConfig({level: 57, rows: 6, columns: 6,
    productTypes: ['watermelon', 'strawberry', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'teddy', 'milk', 'blueJuice', 'greenFruit', 'level3Milk'],
    copiesByType: {watermelon: 3, strawberry: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, teddy: 3, milk: 3, blueJuice: 3, greenFruit: 3, level3Milk: 3},
    targetMatches: 12, difficulty: 'world-2-advanced-entry'}),
  58: levelConfig({level: 58, rows: 6, columns: 6,
    productTypes: ['watermelon', 'strawberry', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'duck', 'can', 'blueMilk', 'greenHerbal', 'orangeCan'],
    copiesByType: {watermelon: 3, strawberry: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, duck: 3, can: 3, blueMilk: 3, greenHerbal: 3, orangeCan: 3},
    targetMatches: 12, difficulty: 'world-2-advanced'}),
  59: levelConfig({level: 59, rows: 6, columns: 6,
    productTypes: ['watermelon', 'strawberry', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'teddy', 'duck', 'blueFruit', 'greenBottle', 'orangeBottle'],
    copiesByType: {watermelon: 3, strawberry: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, teddy: 3, duck: 3, blueFruit: 3, greenBottle: 3, orangeBottle: 3},
    targetMatches: 12, difficulty: 'world-2-advanced-plus'}),
  60: levelConfig({level: 60, rows: 6, columns: 6,
    productTypes: ['watermelon', 'strawberry', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'teddy', 'duck', 'blueJuice', 'greenHerbal', 'redChips'],
    copiesByType: {watermelon: 3, strawberry: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, teddy: 3, duck: 3, blueJuice: 3, greenHerbal: 3, redChips: 3},
    targetMatches: 12, difficulty: 'world-2-milestone'}),
  61: levelConfig({level: 61, rows: 6, columns: 6,
    productTypes: ['watermelon', 'strawberry', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'blueFruit', 'blueJuice', 'greenBottle', 'orangeBottle', 'redChips'],
    copiesByType: {watermelon: 3, strawberry: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, blueFruit: 3, blueJuice: 3, greenBottle: 3, orangeBottle: 3, redChips: 3},
    targetMatches: 12, difficulty: 'world-2-advanced-plus'}),
  62: levelConfig({level: 62, rows: 6, columns: 6,
    productTypes: ['watermelon', 'strawberry', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'teddy', 'can', 'blueMilk', 'greenFruit', 'orangeCan'],
    copiesByType: {watermelon: 3, strawberry: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, teddy: 3, can: 3, blueMilk: 3, greenFruit: 3, orangeCan: 3},
    targetMatches: 12, difficulty: 'world-2-expert-entry'}),
  63: levelConfig({level: 63, rows: 6, columns: 6,
    productTypes: ['watermelon', 'strawberry', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'duck', 'juice', 'blueFruit', 'greenBottle', 'orangeBottleAlt'],
    copiesByType: {watermelon: 3, strawberry: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, duck: 3, juice: 3, blueFruit: 3, greenBottle: 3, orangeBottleAlt: 3},
    targetMatches: 12, difficulty: 'world-2-expert'}),
  64: levelConfig({level: 64, rows: 6, columns: 6,
    productTypes: ['watermelon', 'strawberry', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'teddy', 'duck', 'milk', 'blueJuice', 'level3Milk'],
    copiesByType: {watermelon: 3, strawberry: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, teddy: 3, duck: 3, milk: 3, blueJuice: 3, level3Milk: 3},
    targetMatches: 12, difficulty: 'world-2-expert-plus'}),
  65: levelConfig({level: 65, rows: 6, columns: 6,
    productTypes: ['watermelon', 'strawberry', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'apple', 'can', 'blueMilk', 'greenHerbal', 'redChips'],
    copiesByType: {watermelon: 3, strawberry: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, apple: 3, can: 3, blueMilk: 3, greenHerbal: 3, redChips: 3},
    targetMatches: 12, difficulty: 'world-2-milestone'}),
  66: levelConfig({level: 66, rows: 6, columns: 6,
    productTypes: ['watermelon', 'strawberry', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'apple', 'milk', 'blueFruit', 'greenFruit', 'orangeBottle'],
    copiesByType: {watermelon: 3, strawberry: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, apple: 3, milk: 3, blueFruit: 3, greenFruit: 3, orangeBottle: 3},
    targetMatches: 12, difficulty: 'world-2-master-entry'}),
  67: levelConfig({level: 67, rows: 6, columns: 6,
    productTypes: ['watermelon', 'strawberry', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'duck', 'juice', 'blueJuice', 'greenBottle', 'orangeCan'],
    copiesByType: {watermelon: 3, strawberry: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, duck: 3, juice: 3, blueJuice: 3, greenBottle: 3, orangeCan: 3},
    targetMatches: 12, difficulty: 'world-2-master'}),
  68: levelConfig({level: 68, rows: 6, columns: 6,
    productTypes: ['watermelon', 'strawberry', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'teddy', 'can', 'blueMilk', 'greenHerbal', 'orangeBottleAlt'],
    copiesByType: {watermelon: 3, strawberry: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, teddy: 3, can: 3, blueMilk: 3, greenHerbal: 3, orangeBottleAlt: 3},
    targetMatches: 12, difficulty: 'world-2-master-plus'}),
  69: levelConfig({level: 69, rows: 6, columns: 6,
    productTypes: ['watermelon', 'strawberry', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'teddy', 'duck', 'blueFruit', 'greenBottle', 'orangeBottle'],
    copiesByType: {watermelon: 3, strawberry: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, teddy: 3, duck: 3, blueFruit: 3, greenBottle: 3, orangeBottle: 3},
    targetMatches: 12, difficulty: 'world-2-challenge'}),
  70: levelConfig({level: 70, rows: 6, columns: 6,
    productTypes: ['watermelon', 'strawberry', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'teddy', 'duck', 'blueJuice', 'greenHerbal', 'redChips'],
    copiesByType: {watermelon: 3, strawberry: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, teddy: 3, duck: 3, blueJuice: 3, greenHerbal: 3, redChips: 3},
    targetMatches: 12, difficulty: 'world-2-challenge-milestone'}),
  71: levelConfig({level: 71, rows: 6, columns: 6,
    productTypes: ['apple', 'milk', 'juice', 'can', 'blueFruit', 'blueJuice', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'watermelon'],
    copiesByType: {apple: 3, milk: 3, juice: 3, can: 3, blueFruit: 3, blueJuice: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, watermelon: 3},
    targetMatches: 12, difficulty: 'world-2-expert-entry'}),
  72: levelConfig({level: 72, rows: 6, columns: 6,
    productTypes: ['apple', 'milk', 'blueMilk', 'greenBottle', 'orangeBottle', 'redChips', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'strawberry'],
    copiesByType: {apple: 3, milk: 3, blueMilk: 3, greenBottle: 3, orangeBottle: 3, redChips: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, strawberry: 3},
    targetMatches: 12, difficulty: 'world-2-expert'}),
  73: levelConfig({level: 73, rows: 6, columns: 6,
    productTypes: ['apple', 'juice', 'blueFruit', 'greenFruit', 'orangeCan', 'teddy', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'watermelon'],
    copiesByType: {apple: 3, juice: 3, blueFruit: 3, greenFruit: 3, orangeCan: 3, teddy: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, watermelon: 3},
    targetMatches: 12, difficulty: 'world-2-expert-plus'}),
  74: levelConfig({level: 74, rows: 6, columns: 6,
    productTypes: ['milk', 'can', 'blueJuice', 'greenHerbal', 'level3Milk', 'orangeBottleAlt', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'strawberry'],
    copiesByType: {milk: 3, can: 3, blueJuice: 3, greenHerbal: 3, level3Milk: 3, orangeBottleAlt: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, strawberry: 3},
    targetMatches: 12, difficulty: 'world-2-advanced'}),
  75: levelConfig({level: 75, rows: 6, columns: 6,
    productTypes: ['apple', 'milk', 'juice', 'can', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'watermelon', 'strawberry', 'duck'],
    copiesByType: {apple: 3, milk: 3, juice: 3, can: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, watermelon: 3, strawberry: 3, duck: 3},
    targetMatches: 12, difficulty: 'world-2-milestone'}),
  76: levelConfig({level: 76, rows: 6, columns: 6,
    productTypes: ['blueFruit', 'blueJuice', 'blueMilk', 'greenBottle', 'greenFruit', 'greenHerbal', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'watermelon'],
    copiesByType: {blueFruit: 3, blueJuice: 3, blueMilk: 3, greenBottle: 3, greenFruit: 3, greenHerbal: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, watermelon: 3},
    targetMatches: 12, difficulty: 'world-2-master-entry'}),
  77: levelConfig({level: 77, rows: 6, columns: 6,
    productTypes: ['orangeBottle', 'orangeBottleAlt', 'orangeCan', 'redChips', 'level3Milk', 'teddy', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'strawberry'],
    copiesByType: {orangeBottle: 3, orangeBottleAlt: 3, orangeCan: 3, redChips: 3, level3Milk: 3, teddy: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, strawberry: 3},
    targetMatches: 12, difficulty: 'world-2-master'}),
  78: levelConfig({level: 78, rows: 6, columns: 6,
    productTypes: ['apple', 'milk', 'can', 'blueMilk', 'greenHerbal', 'orangeBottle', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'watermelon'],
    copiesByType: {apple: 3, milk: 3, can: 3, blueMilk: 3, greenHerbal: 3, orangeBottle: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, watermelon: 3},
    targetMatches: 12, difficulty: 'world-2-master-plus'}),
  79: levelConfig({level: 79, rows: 6, columns: 6,
    productTypes: ['blueFruit', 'blueJuice', 'blueMilk', 'greenBottle', 'greenFruit', 'greenHerbal', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'strawberry'],
    copiesByType: {blueFruit: 3, blueJuice: 3, blueMilk: 3, greenBottle: 3, greenFruit: 3, greenHerbal: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, strawberry: 3},
    targetMatches: 12, difficulty: 'world-2-challenge'}),
  80: levelConfig({level: 80, rows: 6, columns: 6,
    productTypes: ['watermelon', 'strawberry', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'teddy', 'duck', 'blueJuice', 'greenHerbal', 'redChips'],
    copiesByType: {watermelon: 3, strawberry: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, teddy: 3, duck: 3, blueJuice: 3, greenHerbal: 3, redChips: 3},
    targetMatches: 12, difficulty: 'world-2-challenge-milestone'}),
  81: levelConfig({level: 81, rows: 6, columns: 6,
    productTypes: ['apple', 'milk', 'juice', 'can', 'blueFruit', 'blueJuice', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'watermelon'],
    copiesByType: {apple: 3, milk: 3, juice: 3, can: 3, blueFruit: 3, blueJuice: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, watermelon: 3},
    targetMatches: 12, difficulty: 'world-2-elite-entry'}),
  82: levelConfig({level: 82, rows: 6, columns: 6,
    productTypes: ['apple', 'milk', 'blueMilk', 'greenBottle', 'orangeBottle', 'redChips', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'strawberry'],
    copiesByType: {apple: 3, milk: 3, blueMilk: 3, greenBottle: 3, orangeBottle: 3, redChips: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, strawberry: 3},
    targetMatches: 12, difficulty: 'world-2-elite'}),
  83: levelConfig({level: 83, rows: 6, columns: 6,
    productTypes: ['blueFruit', 'blueJuice', 'blueMilk', 'greenBottle', 'greenFruit', 'greenHerbal', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'watermelon'],
    copiesByType: {blueFruit: 3, blueJuice: 3, blueMilk: 3, greenBottle: 3, greenFruit: 3, greenHerbal: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, watermelon: 3},
    targetMatches: 12, difficulty: 'world-2-elite-plus'}),
  84: levelConfig({level: 84, rows: 6, columns: 6,
    productTypes: ['orangeBottle', 'orangeBottleAlt', 'orangeCan', 'redChips', 'level3Milk', 'teddy', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'strawberry'],
    copiesByType: {orangeBottle: 3, orangeBottleAlt: 3, orangeCan: 3, redChips: 3, level3Milk: 3, teddy: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, strawberry: 3},
    targetMatches: 12, difficulty: 'world-2-elite-advanced'}),
  85: levelConfig({level: 85, rows: 6, columns: 6,
    productTypes: ['apple', 'milk', 'juice', 'can', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'watermelon', 'strawberry', 'duck'],
    copiesByType: {apple: 3, milk: 3, juice: 3, can: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, watermelon: 3, strawberry: 3, duck: 3},
    targetMatches: 12, difficulty: 'world-2-elite-milestone'}),
  86: levelConfig({level: 86, rows: 6, columns: 6,
    productTypes: ['blueFruit', 'blueJuice', 'blueMilk', 'greenBottle', 'greenFruit', 'greenHerbal', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'strawberry'],
    copiesByType: {blueFruit: 3, blueJuice: 3, blueMilk: 3, greenBottle: 3, greenFruit: 3, greenHerbal: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, strawberry: 3},
    targetMatches: 12, difficulty: 'world-2-legend-entry'}),
  87: levelConfig({level: 87, rows: 6, columns: 6,
    productTypes: ['apple', 'juice', 'blueFruit', 'greenFruit', 'orangeCan', 'teddy', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'watermelon'],
    copiesByType: {apple: 3, juice: 3, blueFruit: 3, greenFruit: 3, orangeCan: 3, teddy: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, watermelon: 3},
    targetMatches: 12, difficulty: 'world-2-legend'}),
  88: levelConfig({level: 88, rows: 6, columns: 6,
    productTypes: ['milk', 'can', 'blueJuice', 'greenHerbal', 'level3Milk', 'orangeBottleAlt', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'strawberry'],
    copiesByType: {milk: 3, can: 3, blueJuice: 3, greenHerbal: 3, level3Milk: 3, orangeBottleAlt: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, strawberry: 3},
    targetMatches: 12, difficulty: 'world-2-legend-plus'}),
  89: levelConfig({level: 89, rows: 6, columns: 6,
    productTypes: ['apple', 'milk', 'can', 'blueMilk', 'greenHerbal', 'orangeBottle', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'watermelon'],
    copiesByType: {apple: 3, milk: 3, can: 3, blueMilk: 3, greenHerbal: 3, orangeBottle: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, watermelon: 3},
    targetMatches: 12, difficulty: 'world-2-legend-challenge'}),
  90: levelConfig({level: 90, rows: 6, columns: 6,
    productTypes: ['watermelon', 'strawberry', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'teddy', 'duck', 'blueJuice', 'greenHerbal', 'redChips'],
    copiesByType: {watermelon: 3, strawberry: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, teddy: 3, duck: 3, blueJuice: 3, greenHerbal: 3, redChips: 3},
    targetMatches: 12, difficulty: 'world-2-legend-challenge-milestone'}),
  91: levelConfig({level: 91, rows: 6, columns: 6,
    productTypes: ['apple', 'milk', 'juice', 'can', 'blueFruit', 'blueJuice', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'watermelon'],
    copiesByType: {apple: 3, milk: 3, juice: 3, can: 3, blueFruit: 3, blueJuice: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, watermelon: 3},
    targetMatches: 12, difficulty: 'world-2-master-elite-entry'}),
  92: levelConfig({level: 92, rows: 6, columns: 6,
    productTypes: ['apple', 'milk', 'blueMilk', 'greenBottle', 'orangeBottle', 'redChips', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'strawberry'],
    copiesByType: {apple: 3, milk: 3, blueMilk: 3, greenBottle: 3, orangeBottle: 3, redChips: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, strawberry: 3},
    targetMatches: 12, difficulty: 'world-2-master-elite'}),
  93: levelConfig({level: 93, rows: 6, columns: 6,
    productTypes: ['blueFruit', 'blueJuice', 'blueMilk', 'greenBottle', 'greenFruit', 'greenHerbal', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'watermelon'],
    copiesByType: {blueFruit: 3, blueJuice: 3, blueMilk: 3, greenBottle: 3, greenFruit: 3, greenHerbal: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, watermelon: 3},
    targetMatches: 12, difficulty: 'world-2-master-elite-plus'}),
  94: levelConfig({level: 94, rows: 6, columns: 6,
    productTypes: ['orangeBottle', 'orangeBottleAlt', 'orangeCan', 'redChips', 'level3Milk', 'teddy', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'strawberry'],
    copiesByType: {orangeBottle: 3, orangeBottleAlt: 3, orangeCan: 3, redChips: 3, level3Milk: 3, teddy: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, strawberry: 3},
    targetMatches: 12, difficulty: 'world-2-master-elite-advanced'}),
  95: levelConfig({level: 95, rows: 6, columns: 6,
    productTypes: ['apple', 'milk', 'juice', 'can', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'watermelon', 'strawberry', 'duck'],
    copiesByType: {apple: 3, milk: 3, juice: 3, can: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, watermelon: 3, strawberry: 3, duck: 3},
    targetMatches: 12, difficulty: 'world-2-master-elite-milestone'}),
  96: levelConfig({level: 96, rows: 6, columns: 6,
    productTypes: ['blueFruit', 'blueJuice', 'blueMilk', 'greenBottle', 'greenFruit', 'greenHerbal', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'strawberry'],
    copiesByType: {blueFruit: 3, blueJuice: 3, blueMilk: 3, greenBottle: 3, greenFruit: 3, greenHerbal: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, strawberry: 3},
    targetMatches: 12, difficulty: 'world-2-final-stretch-entry'}),
  97: levelConfig({level: 97, rows: 6, columns: 6,
    productTypes: ['apple', 'juice', 'blueFruit', 'greenFruit', 'orangeCan', 'teddy', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'watermelon'],
    copiesByType: {apple: 3, juice: 3, blueFruit: 3, greenFruit: 3, orangeCan: 3, teddy: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, watermelon: 3},
    targetMatches: 12, difficulty: 'world-2-final-stretch'}),
  98: levelConfig({level: 98, rows: 6, columns: 6,
    productTypes: ['milk', 'can', 'blueJuice', 'greenHerbal', 'level3Milk', 'orangeBottleAlt', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'strawberry'],
    copiesByType: {milk: 3, can: 3, blueJuice: 3, greenHerbal: 3, level3Milk: 3, orangeBottleAlt: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, strawberry: 3},
    targetMatches: 12, difficulty: 'world-2-final-stretch-plus'}),
  99: levelConfig({level: 99, rows: 6, columns: 6,
    productTypes: ['apple', 'milk', 'can', 'blueMilk', 'greenHerbal', 'orangeBottle', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'watermelon'],
    copiesByType: {apple: 3, milk: 3, can: 3, blueMilk: 3, greenHerbal: 3, orangeBottle: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, watermelon: 3},
    targetMatches: 12, difficulty: 'world-2-pre-finale'}),
  100: levelConfig({level: 100, rows: 6, columns: 6,
    productTypes: ['watermelon', 'strawberry', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'teddy', 'duck', 'blueJuice', 'greenHerbal', 'redChips'],
    copiesByType: {watermelon: 3, strawberry: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, teddy: 3, duck: 3, blueJuice: 3, greenHerbal: 3, redChips: 3},
    targetMatches: 12, difficulty: 'world-2-finale'}),
  101: levelConfig({level: 101, rows: 7, columns: 6,
    productTypes: ['watermelon', 'strawberry', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'blueFruit', 'blueJuice', 'greenBottle', 'orangeBottle', 'redChips', 'milk', 'can'],
    copiesByType: {watermelon: 3, strawberry: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, blueFruit: 3, blueJuice: 3, greenBottle: 3, orangeBottle: 3, redChips: 3, milk: 3, can: 3},
    targetMatches: 14, difficulty: 'world-3-entry'}),
  102: levelConfig({level: 102, rows: 7, columns: 6,
    productTypes: ['watermelon', 'strawberry', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'teddy', 'can', 'blueMilk', 'greenFruit', 'orangeCan', 'juice', 'blueFruit'],
    copiesByType: {watermelon: 3, strawberry: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, teddy: 3, can: 3, blueMilk: 3, greenFruit: 3, orangeCan: 3, juice: 3, blueFruit: 3},
    targetMatches: 14, difficulty: 'world-3-easy'}),
  103: levelConfig({level: 103, rows: 7, columns: 6,
    productTypes: ['watermelon', 'strawberry', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'duck', 'juice', 'blueFruit', 'greenBottle', 'orangeBottleAlt', 'milk', 'blueJuice'],
    copiesByType: {watermelon: 3, strawberry: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, duck: 3, juice: 3, blueFruit: 3, greenBottle: 3, orangeBottleAlt: 3, milk: 3, blueJuice: 3},
    targetMatches: 14, difficulty: 'world-3-easy-plus'}),
  104: levelConfig({level: 104, rows: 7, columns: 6,
    productTypes: ['watermelon', 'strawberry', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'teddy', 'duck', 'milk', 'blueJuice', 'greenFruit', 'can', 'redChips'],
    copiesByType: {watermelon: 3, strawberry: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, teddy: 3, duck: 3, milk: 3, blueJuice: 3, greenFruit: 3, can: 3, redChips: 3},
    targetMatches: 14, difficulty: 'world-3-medium'}),
  105: levelConfig({level: 105, rows: 7, columns: 6,
    productTypes: ['watermelon', 'strawberry', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'apple', 'can', 'blueMilk', 'greenHerbal', 'redChips', 'teddy', 'orangeCan'],
    copiesByType: {watermelon: 3, strawberry: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, apple: 3, can: 3, blueMilk: 3, greenHerbal: 3, redChips: 3, teddy: 3, orangeCan: 3},
    targetMatches: 14, difficulty: 'world-3-milestone'}),
  106: levelConfig({level: 106, rows: 7, columns: 6,
    productTypes: ['watermelon', 'strawberry', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'apple', 'milk', 'blueFruit', 'greenFruit', 'orangeBottle', 'duck', 'blueJuice'],
    copiesByType: {watermelon: 3, strawberry: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, apple: 3, milk: 3, blueFruit: 3, greenFruit: 3, orangeBottle: 3, duck: 3, blueJuice: 3},
    targetMatches: 14, difficulty: 'world-3-advanced-entry'}),
  107: levelConfig({level: 107, rows: 7, columns: 6,
    productTypes: ['watermelon', 'strawberry', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'duck', 'juice', 'blueFruit', 'greenBottle', 'orangeBottleAlt', 'milk', 'blueJuice'],
    copiesByType: {watermelon: 3, strawberry: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, duck: 3, juice: 3, blueFruit: 3, greenBottle: 3, orangeBottleAlt: 3, milk: 3, blueJuice: 3},
    targetMatches: 14, difficulty: 'world-3-advanced'}),
  108: levelConfig({level: 108, rows: 7, columns: 6,
    productTypes: ['watermelon', 'strawberry', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'teddy', 'duck', 'milk', 'blueJuice', 'greenFruit', 'can', 'redChips'],
    copiesByType: {watermelon: 3, strawberry: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, teddy: 3, duck: 3, milk: 3, blueJuice: 3, greenFruit: 3, can: 3, redChips: 3},
    targetMatches: 14, difficulty: 'world-3-advanced-plus'}),
  109: levelConfig({level: 109, rows: 7, columns: 6,
    productTypes: ['watermelon', 'strawberry', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'blueFruit', 'blueMilk', 'greenBottle', 'greenHerbal', 'orangeBottle', 'redChips', 'teddy'],
    copiesByType: {watermelon: 3, strawberry: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, blueFruit: 3, blueMilk: 3, greenBottle: 3, greenHerbal: 3, orangeBottle: 3, redChips: 3, teddy: 3},
    targetMatches: 14, difficulty: 'world-3-milestone'}),
  110: levelConfig({level: 110, rows: 7, columns: 6,
    productTypes: ['watermelon', 'strawberry', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'duck', 'apple', 'juice', 'can', 'greenFruit', 'orangeCan', 'level3Milk'],
    copiesByType: {watermelon: 3, strawberry: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, duck: 3, apple: 3, juice: 3, can: 3, greenFruit: 3, orangeCan: 3, level3Milk: 3},
    targetMatches: 14, difficulty: 'world-3-master-entry'}),
  111: levelConfig({level: 111, rows: 7, columns: 6,
    productTypes: ['watermelon', 'strawberry', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'blueFruit', 'blueJuice', 'blueMilk', 'greenBottle', 'greenFruit', 'orangeBottle', 'redChips'],
    copiesByType: {watermelon: 3, strawberry: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, blueFruit: 3, blueJuice: 3, blueMilk: 3, greenBottle: 3, greenFruit: 3, orangeBottle: 3, redChips: 3},
    targetMatches: 14, difficulty: 'world-3-master'}),
  112: levelConfig({level: 112, rows: 7, columns: 6,
    productTypes: ['watermelon', 'strawberry', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'teddy', 'duck', 'apple', 'milk', 'can', 'greenHerbal', 'orangeBottleAlt'],
    copiesByType: {watermelon: 3, strawberry: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, teddy: 3, duck: 3, apple: 3, milk: 3, can: 3, greenHerbal: 3, orangeBottleAlt: 3},
    targetMatches: 14, difficulty: 'world-3-master-plus'}),
  113: levelConfig({level: 113, rows: 7, columns: 6,
    productTypes: ['watermelon', 'strawberry', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'blueFruit', 'blueJuice', 'blueMilk', 'greenHerbal', 'orangeBottle', 'orangeCan', 'level3Milk'],
    copiesByType: {watermelon: 3, strawberry: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, blueFruit: 3, blueJuice: 3, blueMilk: 3, greenHerbal: 3, orangeBottle: 3, orangeCan: 3, level3Milk: 3},
    targetMatches: 14, difficulty: 'world-3-master-challenge'}),
  114: levelConfig({level: 114, rows: 7, columns: 6,
    productTypes: ['watermelon', 'strawberry', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'teddy', 'duck', 'apple', 'juice', 'can', 'greenBottle', 'redChips'],
    copiesByType: {watermelon: 3, strawberry: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, teddy: 3, duck: 3, apple: 3, juice: 3, can: 3, greenBottle: 3, redChips: 3},
    targetMatches: 14, difficulty: 'world-3-master-challenge-plus'}),
  115: levelConfig({level: 115, rows: 7, columns: 6,
    productTypes: ['watermelon', 'strawberry', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'apple', 'milk', 'blueFruit', 'greenFruit', 'orangeBottleAlt', 'redChips', 'teddy'],
    copiesByType: {watermelon: 3, strawberry: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, apple: 3, milk: 3, blueFruit: 3, greenFruit: 3, orangeBottleAlt: 3, redChips: 3, teddy: 3},
    targetMatches: 14, difficulty: 'world-3-milestone'}),
  116: levelConfig({level: 116, rows: 7, columns: 6,
    productTypes: ['watermelon', 'strawberry', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'duck', 'juice', 'blueJuice', 'blueMilk', 'greenBottle', 'greenHerbal', 'orangeCan'],
    copiesByType: {watermelon: 3, strawberry: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, duck: 3, juice: 3, blueJuice: 3, blueMilk: 3, greenBottle: 3, greenHerbal: 3, orangeCan: 3},
    targetMatches: 14, difficulty: 'world-3-expert-entry'}),
  117: levelConfig({level: 117, rows: 7, columns: 6,
    productTypes: ['watermelon', 'strawberry', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'apple', 'can', 'blueFruit', 'blueJuice', 'greenFruit', 'orangeBottle', 'redChips'],
    copiesByType: {watermelon: 3, strawberry: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, apple: 3, can: 3, blueFruit: 3, blueJuice: 3, greenFruit: 3, orangeBottle: 3, redChips: 3},
    targetMatches: 14, difficulty: 'world-3-expert'}),
  118: levelConfig({level: 118, rows: 7, columns: 6,
    productTypes: ['watermelon', 'strawberry', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'teddy', 'duck', 'milk', 'blueMilk', 'greenBottle', 'greenHerbal', 'orangeBottleAlt'],
    copiesByType: {watermelon: 3, strawberry: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, teddy: 3, duck: 3, milk: 3, blueMilk: 3, greenBottle: 3, greenHerbal: 3, orangeBottleAlt: 3},
    targetMatches: 14, difficulty: 'world-3-expert-plus'}),
  119: levelConfig({level: 119, rows: 7, columns: 6,
    productTypes: ['watermelon', 'strawberry', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'apple', 'juice', 'can', 'blueFruit', 'blueMilk', 'orangeCan', 'level3Milk'],
    copiesByType: {watermelon: 3, strawberry: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, apple: 3, juice: 3, can: 3, blueFruit: 3, blueMilk: 3, orangeCan: 3, level3Milk: 3},
    targetMatches: 14, difficulty: 'world-3-expert-challenge'}),
  120: levelConfig({level: 120, rows: 7, columns: 6,
    productTypes: ['watermelon', 'strawberry', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'apple', 'milk', 'blueFruit', 'blueJuice', 'greenBottle', 'orangeBottle', 'redChips'],
    copiesByType: {watermelon: 3, strawberry: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, apple: 3, milk: 3, blueFruit: 3, blueJuice: 3, greenBottle: 3, orangeBottle: 3, redChips: 3},
    targetMatches: 14, difficulty: 'world-3-milestone'}),
  121: levelConfig({level: 121, rows: 7, columns: 6,
    productTypes: ['watermelon', 'strawberry', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'teddy', 'duck', 'apple', 'can', 'blueMilk', 'greenHerbal', 'orangeCan'],
    copiesByType: {watermelon: 3, strawberry: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, teddy: 3, duck: 3, apple: 3, can: 3, blueMilk: 3, greenHerbal: 3, orangeCan: 3},
    targetMatches: 14, difficulty: 'world-3-master-entry'}),
  122: levelConfig({level: 122, rows: 7, columns: 6,
    productTypes: ['watermelon', 'strawberry', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'duck', 'juice', 'blueFruit', 'greenFruit', 'orangeBottleAlt', 'redChips', 'level3Milk'],
    copiesByType: {watermelon: 3, strawberry: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, duck: 3, juice: 3, blueFruit: 3, greenFruit: 3, orangeBottleAlt: 3, redChips: 3, level3Milk: 3},
    targetMatches: 14, difficulty: 'world-3-master'}),
  123: levelConfig({level: 123, rows: 7, columns: 6,
    productTypes: ['watermelon', 'strawberry', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'blueFruit', 'blueJuice', 'greenBottle', 'orangeBottle', 'redChips', 'caramelTeddy', 'cricketBatBall'],
    copiesByType: {watermelon: 3, strawberry: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, blueFruit: 3, blueJuice: 3, greenBottle: 3, orangeBottle: 3, redChips: 3, caramelTeddy: 3, cricketBatBall: 3},
    targetMatches: 14, difficulty: 'world-3-master-plus'}),
  124: levelConfig({level: 124, rows: 7, columns: 6,
    productTypes: ['watermelon', 'strawberry', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'milk', 'can', 'greenFruit', 'orangeCan', 'blueMilk', 'fieldHockey', 'greenMilkPak'],
    copiesByType: {watermelon: 3, strawberry: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, milk: 3, can: 3, greenFruit: 3, orangeCan: 3, blueMilk: 3, fieldHockey: 3, greenMilkPak: 3},
    targetMatches: 14, difficulty: 'world-3-master-challenge'}),
  125: levelConfig({level: 125, rows: 7, columns: 6,
    productTypes: ['watermelon', 'strawberry', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'apple', 'duck', 'juice', 'greenHerbal', 'orangeBottleAlt', 'redNimcoMix', 'redTomatoPair'],
    copiesByType: {watermelon: 3, strawberry: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, apple: 3, duck: 3, juice: 3, greenHerbal: 3, orangeBottleAlt: 3, redNimcoMix: 3, redTomatoPair: 3},
    targetMatches: 14, difficulty: 'world-3-master-challenge-plus'}),
  126: levelConfig({level: 126, rows: 7, columns: 6,
    productTypes: ['watermelon', 'strawberry', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'blueFruit', 'blueMilk', 'greenBottle', 'orangeBottle', 'redChips', 'olpersMilk', 'shahiNimco'],
    copiesByType: {watermelon: 3, strawberry: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, blueFruit: 3, blueMilk: 3, greenBottle: 3, orangeBottle: 3, redChips: 3, olpersMilk: 3, shahiNimco: 3},
    targetMatches: 14, difficulty: 'world-3-expert-entry'}),
  127: levelConfig({level: 127, rows: 7, columns: 6,
    productTypes: ['watermelon', 'strawberry', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'apple', 'milk', 'juice', 'can', 'orangeCan', 'plushFrog', 'caramelTeddy'],
    copiesByType: {watermelon: 3, strawberry: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, apple: 3, milk: 3, juice: 3, can: 3, orangeCan: 3, plushFrog: 3, caramelTeddy: 3},
    targetMatches: 14, difficulty: 'world-3-expert'}),
  128: levelConfig({level: 128, rows: 7, columns: 6,
    productTypes: ['watermelon', 'strawberry', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'blueJuice', 'greenHerbal', 'orangeBottleAlt', 'level3Milk', 'duck', 'cricketBatBall', 'redTomatoPair'],
    copiesByType: {watermelon: 3, strawberry: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, blueJuice: 3, greenHerbal: 3, orangeBottleAlt: 3, level3Milk: 3, duck: 3, cricketBatBall: 3, redTomatoPair: 3},
    targetMatches: 14, difficulty: 'world-3-expert-plus'}),
  129: levelConfig({level: 129, rows: 7, columns: 6,
    productTypes: ['watermelon', 'strawberry', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'blueFruit', 'blueJuice', 'greenBottle', 'orangeBottle', 'redChips', 'fieldHockey', 'greenMilkPak'],
    copiesByType: {watermelon: 3, strawberry: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, blueFruit: 3, blueJuice: 3, greenBottle: 3, orangeBottle: 3, redChips: 3, fieldHockey: 3, greenMilkPak: 3},
    targetMatches: 14, difficulty: 'world-3-expert-challenge'}),
  130: levelConfig({level: 130, rows: 7, columns: 6,
    productTypes: ['watermelon', 'strawberry', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'apple', 'milk', 'can', 'greenHerbal', 'orangeCan', 'redNimcoMix', 'olpersMilk'],
    copiesByType: {watermelon: 3, strawberry: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, apple: 3, milk: 3, can: 3, greenHerbal: 3, orangeCan: 3, redNimcoMix: 3, olpersMilk: 3},
    targetMatches: 14, difficulty: 'world-3-expert-milestone'}),
  131: levelConfig({level: 131, rows: 7, columns: 6,
    productTypes: ['watermelon', 'strawberry', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'blueFruit', 'blueJuice', 'greenBottle', 'orangeBottle', 'caramelTeddy', 'cricketBatBall', 'fieldHockey'],
    copiesByType: {watermelon: 3, strawberry: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, blueFruit: 3, blueJuice: 3, greenBottle: 3, orangeBottle: 3, caramelTeddy: 3, cricketBatBall: 3, fieldHockey: 3},
    targetMatches: 14, difficulty: 'world-3-master-entry'}),
  132: levelConfig({level: 132, rows: 7, columns: 6,
    productTypes: ['watermelon', 'strawberry', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'apple', 'milk', 'can', 'greenHerbal', 'greenMilkPak', 'redNimcoMix', 'redTomatoPair'],
    copiesByType: {watermelon: 3, strawberry: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, apple: 3, milk: 3, can: 3, greenHerbal: 3, greenMilkPak: 3, redNimcoMix: 3, redTomatoPair: 3},
    targetMatches: 14, difficulty: 'world-3-master'}),
  133: levelConfig({level: 133, rows: 7, columns: 6,
    productTypes: ['watermelon', 'strawberry', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'duck', 'juice', 'blueMilk', 'orangeCan', 'olpersMilk', 'shahiNimco', 'plushFrog'],
    copiesByType: {watermelon: 3, strawberry: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, duck: 3, juice: 3, blueMilk: 3, orangeCan: 3, olpersMilk: 3, shahiNimco: 3, plushFrog: 3},
    targetMatches: 14, difficulty: 'world-3-master-plus'}),
  134: levelConfig({level: 134, rows: 7, columns: 6,
    productTypes: ['watermelon', 'strawberry', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'blueFruit', 'greenBottle', 'orangeBottleAlt', 'redChips', 'caramelTeddy', 'greenMilkPak', 'redNimcoMix'],
    copiesByType: {watermelon: 3, strawberry: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, blueFruit: 3, greenBottle: 3, orangeBottleAlt: 3, redChips: 3, caramelTeddy: 3, greenMilkPak: 3, redNimcoMix: 3},
    targetMatches: 14, difficulty: 'world-3-master-challenge'}),
  135: levelConfig({level: 135, rows: 7, columns: 6,
    productTypes: ['watermelon', 'strawberry', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'apple', 'juice', 'blueMilk', 'orangeCan', 'cricketBatBall', 'fieldHockey', 'redTomatoPair'],
    copiesByType: {watermelon: 3, strawberry: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, apple: 3, juice: 3, blueMilk: 3, orangeCan: 3, cricketBatBall: 3, fieldHockey: 3, redTomatoPair: 3},
    targetMatches: 14, difficulty: 'world-3-master-challenge-plus'}),
  136: levelConfig({level: 136, rows: 7, columns: 6,
    productTypes: ['watermelon', 'strawberry', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'milk', 'can', 'blueJuice', 'greenHerbal', 'olpersMilk', 'shahiNimco', 'plushFrog'],
    copiesByType: {watermelon: 3, strawberry: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, milk: 3, can: 3, blueJuice: 3, greenHerbal: 3, olpersMilk: 3, shahiNimco: 3, plushFrog: 3},
    targetMatches: 14, difficulty: 'world-3-expert-entry'}),
  137: levelConfig({level: 137, rows: 7, columns: 6,
    productTypes: ['watermelon', 'strawberry', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'blueFruit', 'blueJuice', 'greenBottle', 'orangeBottle', 'caramelTeddy', 'fieldHockey', 'olpersMilk'],
    copiesByType: {watermelon: 3, strawberry: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, blueFruit: 3, blueJuice: 3, greenBottle: 3, orangeBottle: 3, caramelTeddy: 3, fieldHockey: 3, olpersMilk: 3},
    targetMatches: 14, difficulty: 'world-3-expert'}),
  138: levelConfig({level: 138, rows: 7, columns: 6,
    productTypes: ['watermelon', 'strawberry', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'apple', 'milk', 'can', 'greenFruit', 'cricketBatBall', 'greenMilkPak', 'shahiNimco'],
    copiesByType: {watermelon: 3, strawberry: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, apple: 3, milk: 3, can: 3, greenFruit: 3, cricketBatBall: 3, greenMilkPak: 3, shahiNimco: 3},
    targetMatches: 14, difficulty: 'world-3-expert-plus'}),
  139: levelConfig({level: 139, rows: 7, columns: 6,
    productTypes: ['watermelon', 'strawberry', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'duck', 'juice', 'blueMilk', 'orangeCan', 'redNimcoMix', 'redTomatoPair', 'plushFrog'],
    copiesByType: {watermelon: 3, strawberry: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, duck: 3, juice: 3, blueMilk: 3, orangeCan: 3, redNimcoMix: 3, redTomatoPair: 3, plushFrog: 3},
    targetMatches: 14, difficulty: 'world-3-expert-challenge'}),
  140: levelConfig({level: 140, rows: 7, columns: 6,
    productTypes: ['watermelon', 'strawberry', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'blueJuice', 'greenHerbal', 'orangeBottleAlt', 'redChips', 'caramelTeddy', 'cricketBatBall', 'redNimcoMix'],
    copiesByType: {watermelon: 3, strawberry: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, blueJuice: 3, greenHerbal: 3, orangeBottleAlt: 3, redChips: 3, caramelTeddy: 3, cricketBatBall: 3, redNimcoMix: 3},
    targetMatches: 14, difficulty: 'world-3-expert-milestone'}),
  141: levelConfig({level: 141, rows: 7, columns: 6,
    productTypes: ['watermelon', 'strawberry', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'blueFruit', 'blueMilk', 'greenBottle', 'orangeBottle', 'fieldHockey', 'greenMilkPak', 'olpersMilk'],
    copiesByType: {watermelon: 3, strawberry: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, blueFruit: 3, blueMilk: 3, greenBottle: 3, orangeBottle: 3, fieldHockey: 3, greenMilkPak: 3, olpersMilk: 3},
    targetMatches: 14, difficulty: 'world-3-master-entry'}),
  142: levelConfig({level: 142, rows: 7, columns: 6,
    productTypes: ['watermelon', 'strawberry', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'apple', 'juice', 'can', 'greenHerbal', 'caramelTeddy', 'redNimcoMix', 'shahiNimco'],
    copiesByType: {watermelon: 3, strawberry: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, apple: 3, juice: 3, can: 3, greenHerbal: 3, caramelTeddy: 3, redNimcoMix: 3, shahiNimco: 3},
    targetMatches: 14, difficulty: 'world-3-master'}),
  143: levelConfig({level: 143, rows: 7, columns: 6,
    productTypes: ['watermelon', 'strawberry', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'duck', 'milk', 'blueJuice', 'orangeCan', 'cricketBatBall', 'redTomatoPair', 'plushFrog'],
    copiesByType: {watermelon: 3, strawberry: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, duck: 3, milk: 3, blueJuice: 3, orangeCan: 3, cricketBatBall: 3, redTomatoPair: 3, plushFrog: 3},
    targetMatches: 14, difficulty: 'world-3-master-plus'}),
  144: levelConfig({level: 144, rows: 7, columns: 6,
    productTypes: ['watermelon', 'strawberry', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'blueFruit', 'blueJuice', 'greenFruit', 'redChips', 'caramelTeddy', 'fieldHockey', 'redNimcoMix'],
    copiesByType: {watermelon: 3, strawberry: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, blueFruit: 3, blueJuice: 3, greenFruit: 3, redChips: 3, caramelTeddy: 3, fieldHockey: 3, redNimcoMix: 3},
    targetMatches: 14, difficulty: 'world-3-master-challenge'}),
  145: levelConfig({level: 145, rows: 7, columns: 6,
    productTypes: ['watermelon', 'strawberry', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'apple', 'milk', 'can', 'orangeBottleAlt', 'cricketBatBall', 'greenMilkPak', 'olpersMilk'],
    copiesByType: {watermelon: 3, strawberry: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, apple: 3, milk: 3, can: 3, orangeBottleAlt: 3, cricketBatBall: 3, greenMilkPak: 3, olpersMilk: 3},
    targetMatches: 14, difficulty: 'world-3-master-challenge-plus'}),
  146: levelConfig({level: 146, rows: 7, columns: 6,
    productTypes: ['watermelon', 'strawberry', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'duck', 'juice', 'blueMilk', 'greenHerbal', 'redTomatoPair', 'shahiNimco', 'plushFrog'],
    copiesByType: {watermelon: 3, strawberry: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, duck: 3, juice: 3, blueMilk: 3, greenHerbal: 3, redTomatoPair: 3, shahiNimco: 3, plushFrog: 3},
    targetMatches: 14, difficulty: 'world-3-expert-entry'}),
  147: levelConfig({level: 147, rows: 7, columns: 6,
    productTypes: ['watermelon', 'strawberry', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'blueFruit', 'greenBottle', 'orangeBottle', 'redChips', 'caramelTeddy', 'cricketBatBall', 'greenMilkPak'],
    copiesByType: {watermelon: 3, strawberry: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, blueFruit: 3, greenBottle: 3, orangeBottle: 3, redChips: 3, caramelTeddy: 3, cricketBatBall: 3, greenMilkPak: 3},
    targetMatches: 14, difficulty: 'world-3-expert'}),
  148: levelConfig({level: 148, rows: 7, columns: 6,
    productTypes: ['watermelon', 'strawberry', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'apple', 'milk', 'greenFruit', 'orangeCan', 'fieldHockey', 'redNimcoMix', 'olpersMilk'],
    copiesByType: {watermelon: 3, strawberry: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, apple: 3, milk: 3, greenFruit: 3, orangeCan: 3, fieldHockey: 3, redNimcoMix: 3, olpersMilk: 3},
    targetMatches: 14, difficulty: 'world-3-expert-plus'}),
  149: levelConfig({level: 149, rows: 7, columns: 6,
    productTypes: ['watermelon', 'strawberry', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'duck', 'juice', 'blueMilk', 'greenHerbal', 'redTomatoPair', 'shahiNimco', 'plushFrog'],
    copiesByType: {watermelon: 3, strawberry: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, duck: 3, juice: 3, blueMilk: 3, greenHerbal: 3, redTomatoPair: 3, shahiNimco: 3, plushFrog: 3},
    targetMatches: 14, difficulty: 'world-3-expert-challenge'}),
  150: levelConfig({level: 150, rows: 7, columns: 6,
    productTypes: ['watermelon', 'strawberry', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'blueJuice', 'can', 'orangeBottleAlt', 'level3Milk', 'caramelTeddy', 'fieldHockey', 'redNimcoMix'],
    copiesByType: {watermelon: 3, strawberry: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, blueJuice: 3, can: 3, orangeBottleAlt: 3, level3Milk: 3, caramelTeddy: 3, fieldHockey: 3, redNimcoMix: 3},
    targetMatches: 14, difficulty: 'world-3-finale'}),
  151: levelConfig({level: 151, rows: 7, columns: 6,
    productTypes: ['watermelon', 'strawberry', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'blueFruit', 'blueJuice', 'greenBottle', 'orangeBottle', 'caramelTeddy', 'fieldHockey', 'olpersMilk'],
    copiesByType: {watermelon: 3, strawberry: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, blueFruit: 3, blueJuice: 3, greenBottle: 3, orangeBottle: 3, caramelTeddy: 3, fieldHockey: 3, olpersMilk: 3},
    targetMatches: 14, difficulty: 'world-4-entry'}),
  152: levelConfig({level: 152, rows: 7, columns: 6,
    productTypes: ['watermelon', 'strawberry', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'apple', 'milk', 'can', 'greenFruit', 'cricketBatBall', 'greenMilkPak', 'shahiNimco'],
    copiesByType: {watermelon: 3, strawberry: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, apple: 3, milk: 3, can: 3, greenFruit: 3, cricketBatBall: 3, greenMilkPak: 3, shahiNimco: 3},
    targetMatches: 14, difficulty: 'world-4-easy'}),
  153: levelConfig({level: 153, rows: 7, columns: 6,
    productTypes: ['watermelon', 'strawberry', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'duck', 'juice', 'blueMilk', 'orangeCan', 'redNimcoMix', 'redTomatoPair', 'plushFrog'],
    copiesByType: {watermelon: 3, strawberry: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, duck: 3, juice: 3, blueMilk: 3, orangeCan: 3, redNimcoMix: 3, redTomatoPair: 3, plushFrog: 3},
    targetMatches: 14, difficulty: 'world-4-easy-plus'}),
  154: levelConfig({level: 154, rows: 7, columns: 6,
    productTypes: ['watermelon', 'strawberry', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'blueFruit', 'greenBottle', 'orangeBottleAlt', 'redChips', 'caramelTeddy', 'greenMilkPak', 'redNimcoMix'],
    copiesByType: {watermelon: 3, strawberry: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, blueFruit: 3, greenBottle: 3, orangeBottleAlt: 3, redChips: 3, caramelTeddy: 3, greenMilkPak: 3, redNimcoMix: 3},
    targetMatches: 14, difficulty: 'world-4-medium'}),
  155: levelConfig({level: 155, rows: 7, columns: 6,
    productTypes: ['watermelon', 'strawberry', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'apple', 'milk', 'can', 'blueJuice', 'cricketBatBall', 'fieldHockey', 'olpersMilk'],
    copiesByType: {watermelon: 3, strawberry: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, apple: 3, milk: 3, can: 3, blueJuice: 3, cricketBatBall: 3, fieldHockey: 3, olpersMilk: 3},
    targetMatches: 14, difficulty: 'world-4-medium-plus'}),
  156: levelConfig({level: 156, rows: 7, columns: 6,
    productTypes: ['watermelon', 'strawberry', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'duck', 'juice', 'blueMilk', 'greenHerbal', 'redTomatoPair', 'shahiNimco', 'plushFrog'],
    copiesByType: {watermelon: 3, strawberry: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, duck: 3, juice: 3, blueMilk: 3, greenHerbal: 3, redTomatoPair: 3, shahiNimco: 3, plushFrog: 3},
    targetMatches: 14, difficulty: 'world-4-advanced-entry'}),
};

export function getStarsForTime(timeLeft, durationSeconds) {
  if (durationSeconds <= 0) return 1;
  const remaining = timeLeft / durationSeconds;
  if (remaining >= 0.35) return 3;
  if (remaining >= 0.15) return 2;
  return 1;
}
